"""

Revision ID: 0cdd4b88b739
Revises: 3a4a139fe95a
Create Date: 2026-07-14 10:38:00.463834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdd4b88b739'
down_revision: Union[str, Sequence[str], None] = '3a4a139fe95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_user_id'), table_name='measurements')
    op.create_index(op.f('ix_measurements_user_id'), 'measurements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_user_id'), table_name='measurements')
    op.create_index(op.f('ix_measurements_user_id'), 'measurements', ['user_id'], unique=True)
    # ### end Alembic commands ###
