"""

Revision ID: 3a4a139fe95a
Revises: e56c44e6474e
Create Date: 2026-07-14 10:29:55.039036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3a4a139fe95a"
down_revision: Union[str, Sequence[str], None] = "e56c44e6474e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "measurements",
        "share_token",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="share_token::uuid",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "measurements",
        "share_token",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
        postgresql_using="share_token::text",
    )
    # ### end Alembic commands ###
